name: Run GitHub Issue Scraper
on:
  workflow_dispatch:
  schedule:
    # Run every 3 hours
    - cron: "0 */3 * * *"
jobs:
  issue-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.36.0
          cache: true
      - name: Install Dependencies
        run: pixi install
      # Step 4: Run the GitHub issue scraper script
      - name: Run GitHub Issue Scraper
        run: pixi run python get_issues.py
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          INDEX_NAME: github_issues
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update formatted_issues.json"
          file_pattern: formatted_issues.json
          skip_dirty_check: false
        
